layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 4
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: connorslagle
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Tableau
    web_url: https://www.tableau.com/why-tableau
    image_url: https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.avalonrisk.com%2Fimages%2Ficons%2Ftabl.png&f=1&nofb=1

  - name: Coral
    web_url: https://www.coral.ai/about-coral/
    image_url: https://media.istockphoto.com/vectors/coral-logo-isolated-coral-on-white-background-vector-id1063689100?k=6&m=1063689100&s=170667a&w=0&h=AmA3emZgoV-DeGiYOKCrDSOZ-7DvzjVTfvj6dzt93kE=

  - name: PyTorch
    web_url: https://pytorch.org/features/
    image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpytorch.org%2Fassets%2Fimages%2Fpytorch-logo.png&f=1&nofb=1

  - name: React Native
    web_url: https://reactnative.dev/
    image_url: http://www.kiodev.com/wp-content/uploads/2016/03/react-logo.png
